/**
 * Demo package: slowczech episode 317 "Potkala jsem medvěda!" → case practice.
 *
 * Hand-curated from scripts/demo/slowczech_317.review.md (MorphoDiTa tagger
 * output). Every item was proofread against the transcript. Forms are drilled
 * AS THEY APPEAR IN THE STORY — `overrideForm` makes a colloquial form the
 * primary answer while the standard form stays accepted.
 *
 * Copy marked `TODO(copy)` is a placeholder slot for the final partner-facing
 * wording.
 */
import type { Case, Number_, WordEntry } from '$lib/types';

export const SLUG = 'slowczech-medved-915094';

export interface DemoMeta {
	title: string;
	subtitle: string;
	storyTitle: string;
	narrator: string;
	episode: number;
	sourceUrl: string;
	spotifyUrl: string;
	partnerName: string;
	partnerUrl: string;
	introCopy: string;
	closingTitle: string;
	closingCopy: string[];
}

interface DemoItemBase {
	/** Stable id, also used as the template id (shuffle seed for case options). */
	id: string;
	lemma: string;
	case: Case;
	number: Number_;
	/** Explanation shown after answering. */
	why: string;
	/** Colloquial / as-in-story form to use as the primary answer. */
	overrideForm?: string;
	/** Extra accepted spellings for this slot (e.g. the standard form). */
	acceptAlso?: string[];
}

export type DemoItem =
	| (DemoItemBase & {
			kind: 'sentence';
			/** Sentence with `___` where the noun goes. */
			template: string;
			source: 'verbatim' | 'inspired';
	  })
	| (DemoItemBase & {
			kind: 'identify';
			template: string;
			source: 'verbatim' | 'inspired';
			/** Exactly three case buttons to offer (correct + two distractors). */
			caseOptions: [Case, Case, Case];
	  })
	| (DemoItemBase & { kind: 'form' });

export interface DemoSectionDef {
	id: string;
	/**
	 * Standard two-part heading: [Czech question word(s), English case name],
	 * e.g. ["Koho?", "Accusative"]. Used for the picker (two lines) and the
	 * drill header (one line).
	 */
	label: [string, string];
	emoji: string;
	/** One English line: what this case is for (no answers given away). */
	usage: string;
	blurb: string;
	items: DemoItem[];
	/** Ids of items from other sections to re-drill here (mixed review). */
	reuse?: string[];
}

export interface DemoPackage {
	meta: DemoMeta;
	story: string[];
	localWords: WordEntry[];
	sections: DemoSectionDef[];
}

/* ------------------------------------------------------------------ */
/* Nouns from the story that are not (yet) in word_bank.json.          */
/* Forms generated by MorphoDiTa via scripts/demo/analyze_transcript.py */
/* and proofread. Proper nouns deliberately stay local to this demo.   */
/* ------------------------------------------------------------------ */
const localWords: WordEntry[] = [
	{
		lemma: 'kamzík',
		translation: 'chamois',
		gender: 'm',
		animate: true,
		paradigm: 'pán',
		difficulty: 'B1',
		categories: ['animals'],
		forms: {
			sg: ['kamzík', 'kamzíka', 'kamzíkovi', 'kamzíka', 'kamzíku', 'kamzíkovi', 'kamzíkem'],
			pl: ['kamzíci', 'kamzíků', 'kamzíkům', 'kamzíky', 'kamzíci', 'kamzících', 'kamzíky']
		},
		variantForms: { sg: { 2: ['kamzíku'], 5: ['kamzíku'] } }
	},
	{
		lemma: 'muflon',
		translation: 'mouflon',
		gender: 'm',
		animate: true,
		paradigm: 'pán',
		difficulty: 'B1',
		categories: ['animals'],
		forms: {
			sg: ['muflon', 'muflona', 'muflonovi', 'muflona', 'muflone', 'muflonovi', 'muflonem'],
			pl: ['mufloni', 'muflonů', 'muflonům', 'muflony', 'mufloni', 'muflonech', 'muflony']
		},
		variantForms: { sg: { 2: ['muflonu'], 5: ['muflonu'] } }
	},
	{
		lemma: 'túra',
		translation: 'hike',
		gender: 'f',
		animate: false,
		paradigm: 'žena',
		difficulty: 'B1',
		categories: ['activities'],
		forms: {
			sg: ['túra', 'túry', 'túře', 'túru', 'túro', 'túře', 'túrou'],
			pl: ['túry', 'túr', 'túrám', 'túry', 'túry', 'túrách', 'túrami']
		}
	},
	{
		lemma: 'foťák',
		translation: 'camera (colloquial)',
		gender: 'm',
		animate: false,
		paradigm: 'hrad',
		difficulty: 'B1',
		categories: ['objects'],
		forms: {
			sg: ['foťák', 'foťáku', 'foťáku', 'foťák', 'foťáku', 'foťáku', 'foťákem'],
			pl: ['foťáky', 'foťáků', 'foťákům', 'foťáky', 'foťáky', 'foťácích', 'foťáky']
		}
	},
	{
		lemma: 'hvězdička',
		translation: 'little star (rating)',
		gender: 'f',
		animate: false,
		paradigm: 'žena',
		difficulty: 'B1',
		categories: ['objects'],
		forms: {
			sg: [
				'hvězdička',
				'hvězdičky',
				'hvězdičce',
				'hvězdičku',
				'hvězdičko',
				'hvězdičce',
				'hvězdičkou'
			],
			pl: [
				'hvězdičky',
				'hvězdiček',
				'hvězdičkám',
				'hvězdičky',
				'hvězdičky',
				'hvězdičkách',
				'hvězdičkami'
			]
		}
	},
	{
		lemma: 'Slovensko',
		translation: 'Slovakia',
		gender: 'n',
		animate: false,
		paradigm: 'město',
		difficulty: 'A2',
		categories: ['places'],
		forms: {
			sg: [
				'Slovensko',
				'Slovenska',
				'Slovensku',
				'Slovensko',
				'Slovensko',
				'Slovensku',
				'Slovenskem'
			],
			pl: ['', '', '', '', '', '', '']
		}
	},
	{
		lemma: 'Tatry',
		translation: 'the Tatra Mountains',
		gender: 'f',
		animate: false,
		paradigm: 'žena',
		difficulty: 'A2',
		categories: ['places'],
		pluralOnly: true,
		forms: {
			sg: ['', '', '', '', '', '', ''],
			pl: ['Tatry', 'Tater', 'Tatrám', 'Tatry', 'Tatry', 'Tatrách', 'Tatrami']
		}
	}
];

/* ------------------------------------------------------------------ */
/* Story text — © slowczech, reproduced for this partner demo only.     */
/* ------------------------------------------------------------------ */
const story: string[] = [
	'Ahoj, dneska mám pro tebe příběh. Potkala jsem medvěda. Chceš taky umět vyprávět historky ze svého života? Tak poslouchej dál.',
	'Už je to několik roků, co jsem jela s manželem na Slovensko. Chtěli jsme navštívit Tatry. Tatry jsou krásné hory.',
	'Bylo už po sezóně, takže tam nebyli moc turisti. Šli jsme na túru. Turisty jsme opravdu neviděli, ale viděli jsme horská zvířata. Nejdřív jsme viděli kamzíky a muflony. To jsou horský kozy. Věděli jsme, že tam jsou i medvědi, ale nečekali jsme, že medvěda uvidíme.',
	'A potom se manžel zastavil a říká, podívej, támhle je medvěd. Nejdřív jsem mu nevěřila, ale pak jsem se podívala a uviděla jsem ho taky. Byl veliký a byl docela blízko. Asi 300 metrů a šel k nám. Nevěděla jsem, co mám dělat. Byla jsem totálně paralyzovaná. Když jsem se zeptala manžela, co mám dělat, dal mi do ruky foťák a řekl, foť.',
	'A tak jsem fotila. Medvěd o nás nevěděl. Chvíli jsme tam stáli a dívali se na něj a potom jsme šli dál. Byl to ale adrenalin. A to není všechno.',
	'Když jsme potom přišli do vesnice, museli jsme stopovat auta, protože vlak ani autobus už žádný nejel. No a koho jsme si stopli? Policajty. Z dálky jsme neviděli, že je to policejní auto a když byli blízko a už jsme věděli, že je to policie, tak už zastavovali.',
	'Takže nás domů dovezli policajti a v autě jsme jim ukazovali naše video medvěda. Nemohli tomu uvěřit. Říkali, že chodí do hor často, ale medvěda tam nikdy nepotkali.',
	'A co ty? Umíš vyprávět historky v češtině nebo ti chybí slova, když mluvíš česky? S tím ti ve slowczech rádi pomůžeme. Přidej se k nám a taky nám dej hvězdičku na Spotify a řekni o nás svým kamarádům, co se učí česky. Nás tak budeš motivovat dělat to, co děláme a kamarádům pomůžeš zlepšit si češtinu a bavit se přitom.'
];

/* ------------------------------------------------------------------ */
/* Drill sections                                                      */
/* ------------------------------------------------------------------ */
const sections: DemoSectionDef[] = [
	{
		id: 'acc',
		label: ['Koho? Co?', 'Accusative'],
		emoji: '🐻',
		usage: 'The direct object — whom or what the action lands on.',
		blurb:
			'TODO(copy) The classic freeze point: masculine animate nouns change in the accusative (medvěd → medvěda). This story is full of them. 🐻',
		items: [
			{
				id: 'acc-01',
				kind: 'sentence',
				lemma: 'medvěd',
				case: 'acc',
				number: 'sg',
				template: 'Potkala jsem ___.',
				source: 'verbatim',
				why: 'Potkala jsem koho? → accusative. Medvěd is a pán-type noun (masc. animate): acc. sg. = gen. sg., ending -a → medvěda.'
			},
			{
				id: 'acc-02',
				kind: 'sentence',
				lemma: 'medvěd',
				case: 'acc',
				number: 'sg',
				template: 'Nečekali jsme, že ___ uvidíme.',
				source: 'verbatim',
				why: '…že koho uvidíme? → accusative. Pán-type (masc. animate): acc. sg. borrows the genitive -a → medvěda.'
			},
			{
				id: 'acc-03',
				kind: 'sentence',
				lemma: 'turista',
				case: 'acc',
				number: 'pl',
				template: '___ jsme opravdu neviděli.',
				source: 'verbatim',
				why: 'Koho jsme neviděli? → accusative plural. Turista is předseda-type: acc. pl. -y → turisty (nom. pl. turisté / turisti loses its animate ending).'
			},
			{
				id: 'acc-04',
				kind: 'sentence',
				lemma: 'kamzík',
				case: 'acc',
				number: 'pl',
				template: 'Nejdřív jsme viděli ___ a muflony.',
				source: 'verbatim',
				why: 'Viděli jsme koho? → accusative plural. Kamzík is pán-type: acc. pl. -y → kamzíky (nom. pl. kamzíci), same -y as „muflony“ next to it.'
			},
			{
				id: 'acc-05',
				kind: 'sentence',
				lemma: 'muflon',
				case: 'acc',
				number: 'pl',
				template: 'Nejdřív jsme viděli kamzíky a ___.',
				source: 'verbatim',
				why: 'Second object of viděli jsme → accusative plural. Muflon, pán-type: acc. pl. -y → muflony (nom. pl. mufloni).'
			},
			{
				id: 'acc-06',
				kind: 'sentence',
				lemma: 'policajt',
				case: 'acc',
				number: 'pl',
				template: 'No a koho jsme si stopli? ___.',
				source: 'verbatim',
				why: 'Koho jsme si stopli? — the answer keeps the question’s case: accusative plural (the object of stopli jsme si). Policajt, pán-type: acc. pl. -y → policajty. As the subject later they’re „policajti“ (nom. pl. -i).'
			},
			{
				id: 'acc-07',
				kind: 'sentence',
				lemma: 'auto',
				case: 'acc',
				number: 'pl',
				template: 'Museli jsme stopovat ___.',
				source: 'verbatim',
				why: 'Stopovat co? → accusative plural. Auto is město-type (neuter): acc. pl. = nom. pl. → auta. In the plural, only masculine animate nouns have a distinct accusative form.'
			},
			{
				id: 'acc-08',
				kind: 'sentence',
				lemma: 'zvíře',
				case: 'acc',
				number: 'pl',
				template: 'Viděli jsme horská ___.',
				source: 'verbatim',
				why: 'Viděli jsme co? → accusative plural. Zvíře is kuře-type (neuter, stem -at- in the plural): nom./acc. pl. → zvířata.'
			},
			{
				id: 'acc-09',
				kind: 'sentence',
				lemma: 'Tatry',
				case: 'acc',
				number: 'pl',
				template: 'Chtěli jsme navštívit ___.',
				source: 'verbatim',
				why: 'Navštívit co? → accusative. Tatry: feminine žena-type, plural-only; acc. pl. = nom. pl. → Tatry.'
			},
			{
				id: 'acc-10',
				kind: 'sentence',
				lemma: 'hvězdička',
				case: 'acc',
				number: 'sg',
				template: 'Dej nám ___ na Spotify! ⭐',
				source: 'inspired',
				why: 'Dej nám co? → accusative. Hvězdička is žena-type: acc. sg. -a → -u → hvězdičku.'
			},
			{
				id: 'acc-13',
				kind: 'form',
				lemma: 'medvěd',
				case: 'acc',
				number: 'sg',
				why: 'medvěd → medvěda: pán-type (masc. animate) acc. sg. = gen. sg., ending -a. The whole story turns on it: „Potkala jsem medvěda“.'
			},
			{
				id: 'acc-14',
				kind: 'form',
				lemma: 'policajt',
				case: 'acc',
				number: 'pl',
				why: 'policajt → policajty: pán-type acc. pl. takes -y („koho jsme si stopli? Policajty“); the nom. pl. is policajti („dovezli nás policajti“).'
			}
		]
	},
	{
		id: 'ins',
		label: ['S kým? Čím?', 'Instrumental'],
		emoji: '🚔',
		usage: 'Company and means — with whom, by what, using what.',
		blurb:
			'TODO(copy) „Jela jsem s manželem na Slovensko" — with whom, by what. Sentences marked „inspired" reuse the story’s words in new contexts.',
		items: [
			{
				id: 'ins-01',
				kind: 'sentence',
				lemma: 'manžel',
				case: 'ins',
				number: 'sg',
				template: 'Jela jsem s ___ na Slovensko.',
				source: 'verbatim',
				why: 'Jela jsem s kým? → s (with) takes the instrumental. Manžel, pán-type: ins. sg. -em → s manželem.'
			},
			{
				id: 'ins-02',
				kind: 'sentence',
				lemma: 'kamarád',
				case: 'ins',
				number: 'pl',
				template: 'Šli jsme na túru s ___.',
				source: 'inspired',
				why: 'Šli jsme s kým? → s + instrumental plural. Kamarád, pán-type: ins. pl. -y → s kamarády (looks like acc. pl.; the s makes it instrumental).'
			},
			{
				id: 'ins-03',
				kind: 'sentence',
				lemma: 'auto',
				case: 'ins',
				number: 'sg',
				template: 'Domů nás policajti dovezli ___.',
				source: 'inspired',
				why: 'Dovezli nás čím? → means of transport, instrumental with no preposition. Auto, město-type: ins. sg. -em → autem.'
			},
			{
				id: 'ins-04',
				kind: 'sentence',
				lemma: 'foťák',
				case: 'ins',
				number: 'sg',
				template: 'Fotila jsem ___, který mi dal manžel.',
				source: 'inspired',
				why: 'Fotila jsem čím? → the tool you use, instrumental with no preposition. Foťák, hrad-type: ins. sg. -em → foťákem.'
			},
			{
				id: 'ins-05',
				kind: 'sentence',
				lemma: 'vlak',
				case: 'ins',
				number: 'sg',
				template: 'Nejeli jsme ani ___, ani autobusem.',
				source: 'inspired',
				why: 'Nejeli jsme čím? → means of transport, instrumental. Vlak, hrad-type: ins. sg. -em → vlakem (like „autobusem“ at the end).'
			},
			{
				id: 'ins-06',
				kind: 'sentence',
				lemma: 'medvěd',
				case: 'ins',
				number: 'sg',
				template: 'Setkali jsme se s ___ v Tatrách.',
				source: 'inspired',
				why: 'Setkali jsme se s kým? → setkat se s + instrumental. Medvěd, pán-type: ins. sg. -em → s medvědem.'
			},
			{
				id: 'ins-07',
				kind: 'form',
				lemma: 'manžel',
				case: 'ins',
				number: 'sg',
				why: 'manžel → manželem: pán-type ins. sg. takes -em („jela jsem s manželem“).'
			}
		]
	},
	{
		id: 'dir',
		label: ['Kam? Kde?', 'Direction & location'],
		emoji: '🏔️',
		usage: 'Going somewhere vs. being somewhere — the preposition picks the case.',
		blurb:
			'TODO(copy) na Slovensko, na túru (kam? → accusative) · do vesnice, do hor (kam? → do + genitive) · po sezóně, v autě (kde? / kdy? → locative).',
		items: [
			{
				id: 'dir-01',
				kind: 'sentence',
				lemma: 'Slovensko',
				case: 'acc',
				number: 'sg',
				template: 'Jela jsem s manželem na ___.',
				source: 'verbatim',
				why: 'Jela jsem kam? → na + accusative for direction. Slovensko, město-type (neuter): acc. sg. = nom. sg. → na Slovensko. Kde? would be na Slovensku (loc.).'
			},
			{
				id: 'dir-02',
				kind: 'sentence',
				lemma: 'túra',
				case: 'acc',
				number: 'sg',
				template: 'Šli jsme na ___.',
				source: 'verbatim',
				why: 'Šli jsme kam? → na + accusative for a goal. Túra, žena-type: acc. sg. -u → na túru.'
			},
			{
				id: 'dir-03',
				kind: 'sentence',
				lemma: 'sezóna',
				case: 'loc',
				number: 'sg',
				template: 'Bylo už po ___.',
				source: 'verbatim',
				why: 'Bylo po čem? → po (after) + locative. Sezóna, žena-type: loc. sg. -ě → po sezóně.'
			},
			{
				id: 'dir-04',
				kind: 'sentence',
				lemma: 'vesnice',
				case: 'gen',
				number: 'sg',
				template: 'Když jsme potom přišli do ___, museli jsme stopovat auta.',
				source: 'verbatim',
				why: 'Přišli jsme kam? → do (into) takes the genitive even for direction. Vesnice, růže-type: gen. sg. = nom. sg. -e → do vesnice.'
			},
			{
				id: 'dir-05',
				kind: 'sentence',
				lemma: 'ruka',
				case: 'gen',
				number: 'sg',
				template: 'Dal mi do ___ foťák a řekl: foť!',
				source: 'verbatim',
				why: 'Dal mi foťák kam? → do + genitive. Ruka, žena-type: gen. sg. -y → do ruky.'
			},
			{
				id: 'dir-06',
				kind: 'sentence',
				lemma: 'auto',
				case: 'loc',
				number: 'sg',
				template: 'V ___ jsme jim ukazovali naše video.',
				source: 'verbatim',
				why: 'Ukazovali jsme kde? → v + locative (no movement). Auto, město-type: loc. sg. -ě → v autě.'
			},
			{
				id: 'dir-07',
				kind: 'sentence',
				lemma: 'hora',
				case: 'gen',
				number: 'pl',
				template: 'Říkali, že chodí do ___ často.',
				source: 'verbatim',
				why: 'Chodí kam? → do + genitive plural. Hora, žena-type: gen. pl. drops the ending → do hor.'
			},
			{
				id: 'dir-08',
				kind: 'sentence',
				lemma: 'dálka',
				case: 'gen',
				number: 'sg',
				template: 'Z ___ jsme neviděli, že je to policejní auto.',
				source: 'verbatim',
				why: 'Neviděli jsme odkud? → z (from) + genitive. Dálka, žena-type: gen. sg. -y → z dálky.'
			},
			{
				id: 'dir-09',
				kind: 'sentence',
				lemma: 'čeština',
				case: 'loc',
				number: 'sg',
				template: 'Umíš vyprávět historky v ___?',
				source: 'verbatim',
				why: 'Historky v čem? → v + locative for the language. Čeština, žena-type: loc. sg. -ě → v češtině.'
			},
			{
				id: 'dir-10',
				kind: 'sentence',
				lemma: 'život',
				case: 'gen',
				number: 'sg',
				template: 'Chceš umět vyprávět historky ze svého ___?',
				source: 'verbatim',
				why: 'Historky ze svého čeho? → z/ze + genitive. Život is hrad-type but one of the nouns with gen. sg. -a (not -u) → ze života.'
			}
		]
	},
	{
		id: 'mix',
		label: ['Všechno', 'Mixed review'],
		emoji: '🔁',
		usage: 'All of the above, shuffled — plus a few “which case?” questions.',
		blurb: 'TODO(copy) A quick pass across everything — plus two extra cases hiding in the story.',
		items: [
			{
				id: 'mix-01',
				kind: 'sentence',
				lemma: 'kamarád',
				case: 'dat',
				number: 'pl',
				template: 'Řekni o nás svým ___!',
				source: 'verbatim',
				why: 'Řekni komu? → říct + dative for the person told. Kamarád, pán-type: dat. pl. -ům → svým kamarádům.'
			},
			{
				id: 'mix-02',
				kind: 'sentence',
				lemma: 'manžel',
				case: 'gen',
				number: 'sg',
				template: 'Když jsem se zeptala ___, co mám dělat, dal mi do ruky foťák.',
				source: 'verbatim',
				why: 'Zeptala jsem se koho? → zeptat se + genitive. Manžel, pán-type: gen. sg. -a → manžela (identical to the acc. sg.).'
			},
			{
				id: 'mix-03',
				kind: 'sentence',
				lemma: 'turista',
				case: 'nom',
				number: 'pl',
				template: 'Bylo už po sezóně, takže tam nebyli moc ___.',
				source: 'verbatim',
				// Spoken Czech, exactly as in the story. The textbook form is accepted too.
				overrideForm: 'turisti',
				acceptAlso: ['turisté'],
				why: 'Kdo tam nebyl? → subject, nominative plural. Turista, předseda-type: nom. pl. turisté — but Veronika says turisti, everyday spoken Czech (hovorová čeština); both are accepted.'
			},
			{
				id: 'acc-11',
				kind: 'identify',
				lemma: 'medvěd',
				case: 'gen',
				number: 'sg',
				template: 'V autě jsme jim ukazovali naše video ___.',
				source: 'verbatim',
				caseOptions: ['acc', 'gen', 'nom'],
				why: '„naše video medvěda“ = the video *of* the bear → genitive (one noun owning another), not the object of ukazovali. Pán-type gen. sg. -a is identical to the acc. sg. — the meaning decides.'
			},
			{
				id: 'acc-12',
				kind: 'identify',
				lemma: 'medvěd',
				case: 'acc',
				number: 'sg',
				template: 'Policajti ___ tam nikdy nepotkali.',
				source: 'inspired',
				caseOptions: ['acc', 'gen', 'nom'],
				why: 'Policajti nepotkali koho? → accusative: medvěda is the object of nepotkali. Pán-type acc. sg. -a, same shape as the genitive.'
			},
			{
				id: 'dir-11',
				kind: 'identify',
				lemma: 'Slovensko',
				case: 'loc',
				number: 'sg',
				template: 'Byli jsme na ___ a viděli jsme medvěda.',
				source: 'inspired',
				caseOptions: ['acc', 'loc', 'gen'],
				why: 'Byli jsme kde? → no movement, na + locative. Slovensko, město-type: loc. sg. -u → na Slovensku (kam? would be na Slovensko, acc.).'
			},
			{
				id: 'dir-12',
				kind: 'identify',
				lemma: 'vesnice',
				case: 'gen',
				number: 'sg',
				template: 'Přišli jsme do ___.',
				source: 'verbatim',
				caseOptions: ['gen', 'loc', 'acc'],
				why: 'Přišli jsme kam? → do + genitive. Vesnice, růže-type: gen. sg. -e → do vesnice (kde? = ve vesnici, loc.).'
			},
			{
				id: 'dir-13',
				kind: 'identify',
				lemma: 'vesnice',
				case: 'loc',
				number: 'sg',
				template: 'Ve ___ jsme stopovali auta.',
				source: 'inspired',
				caseOptions: ['gen', 'loc', 'acc'],
				why: 'Stopovali jsme kde? → ve + locative. Vesnice, růže-type: loc. sg. -i → ve vesnici (kam? = do vesnice, gen.).'
			}
		],
		reuse: ['acc-01', 'ins-01', 'dir-02', 'acc-06', 'dir-06', 'ins-03', 'dir-07']
	}
];

export const demoPackage: DemoPackage = {
	meta: {
		title: 'Potkala jsem medvěda',
		subtitle:
			'You’ve heard the story, now decline it! Stop memorizing cases and instead practice declension through natural repetition.',
		storyTitle: 'Potkala jsem medvěda!',
		narrator: 'Veronika',
		episode: 317,
		sourceUrl: 'https://slowczech.com/learn-czech-bear-story/',
		spotifyUrl: 'https://open.spotify.com/show/6oylf2ljLhnt67G3cOge4b',
		partnerName: 'slowczech',
		partnerUrl: 'https://slowczech.com/',
		introCopy:
			'TODO(copy) Listen to (or read) the story first, then practise the cases with the story’s own words. Every drill below was generated from the transcript. 🎧🐻',
		closingTitle: 'TODO(copy) How this works',
		closingCopy: [
			'TODO(copy) Transcript in → drills out. We run the story through a morphological analyser (MorphoDiTa, Charles University) that tags every noun and adjective with its case, number and gender, then Skloňuj turns those into fill-in, form-recall and „which case?" drills — grouped by the patterns the story actually uses.',
			'TODO(copy) It works for any episode — past and future — and keeps the forms exactly as they are spoken, hovorová čeština included. The „listen again" button that never runs out.'
		]
	},
	story,
	localWords,
	sections
};
